@startwbs CUI券売機シミュレーターを作るwbs
title cui券売機シミュレーターを作るwbs
+ CUI券売機シミュレーターを作る

** タイトルを表示させる
+++ タイトルを表示させる
*** キーイベントを作る

** シミュレーション画面を作る
+++ メニューを表示させる
*** 商品番号を入力させる
*** お会計をする

** 管理画面を作る
+++ 売上を表示する
*** 管理メニューを作る

@endwbs
 